"""extend approval workflow

Revision ID: 28a5e98a1a7d
Revises: 85d3968e9db8
Create Date: 2026-08-15 10:13:23.256578
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "28a5e98a1a7d"
down_revision: str | None = "85d3968e9db8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals") as batch_op:
        batch_op.add_column(
            sa.Column(
                "requested_reason",
                sa.Text(),
                server_default="Legacy approval request",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("workflow_run_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("resumed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            op.f("ix_approvals_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            op.f("fk_approvals_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_approvals_workflow_run_id_workflow_runs"), type_="foreignkey"
        )
        batch_op.drop_index(op.f("ix_approvals_workflow_run_id"))
        batch_op.drop_column("resumed_at")
        batch_op.drop_column("workflow_run_id")
        batch_op.drop_column("requested_reason")
    # ### end Alembic commands ###
