"""add initial domain models

Revision ID: 3c43db34f536
Revises: 20260815_0001
Create Date: 2026-08-15 10:03:17.388768
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3c43db34f536"
down_revision: str | None = "20260815_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("requested_payload", sa.JSON(), nullable=False),
        sa.Column("action_hash", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=50), nullable=False),
        sa.Column("rule_name", sa.String(length=255), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "approved",
                "rejected",
                "expired",
                "cancelled",
                "executed",
                "execution_failed",
                name="approval_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "resource_type", "resource_id", "action_hash", name=op.f("uq_approvals_resource_type")
        ),
    )
    op.create_index(op.f("ix_approvals_action_type"), "approvals", ["action_type"], unique=False)
    op.create_index(op.f("ix_approvals_expires_at"), "approvals", ["expires_at"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_resource",
        "audit_events",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "domain_events",
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("producer", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "publication_status",
            sa.Enum(
                "pending",
                "published",
                "failed",
                "dead_lettered",
                name="event_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publication_attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_events")),
        sa.UniqueConstraint(
            "aggregate_type",
            "aggregate_id",
            "aggregate_version",
            "event_type",
            name=op.f("uq_domain_events_aggregate_type"),
        ),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_domain_events_idempotency_key")),
    )
    op.create_index(
        op.f("ix_domain_events_correlation_id"), "domain_events", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_domain_events_event_type"), "domain_events", ["event_type"], unique=False
    )
    op.create_index(
        "ix_domain_events_outbox",
        "domain_events",
        ["publication_status", "created_at"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("marketplace", sa.String(length=100), nullable=False),
        sa.Column("marketplace_account_id", sa.String(length=255), nullable=False),
        sa.Column("external_order_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "paid",
                "processing",
                "dispatched",
                "delivered",
                "cancelled",
                "returned",
                "refunded",
                name="order_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("customer_reference", sa.String(length=255), nullable=True),
        sa.Column("shipping_details", sa.JSON(), nullable=False),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_orders_nonnegative_total")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "marketplace",
            "marketplace_account_id",
            "external_order_id",
            name=op.f("uq_orders_marketplace"),
        ),
    )
    op.create_index(op.f("ix_orders_ordered_at"), "orders", ["ordered_at"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "products",
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("external_product_id", sa.String(length=255), nullable=False),
        sa.Column("source_workflow_run_id", sa.String(length=255), nullable=False),
        sa.Column("source_recommendation_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("identifiers", sa.JSON(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("recommendation_evidence", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("approved", "archived", name="product_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint(
            "source_system", "external_product_id", name=op.f("uq_products_source_system")
        ),
    )
    op.create_index(
        op.f("ix_products_source_workflow_run_id"),
        "products",
        ["source_workflow_run_id"],
        unique=False,
    )
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_table(
        "suppliers",
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("external_supplier_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("contact_details", sa.JSON(), nullable=False),
        sa.Column("terms", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="supplier_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint(
            "source_system", "external_supplier_id", name=op.f("uq_suppliers_source_system")
        ),
    )
    op.create_index(op.f("ix_suppliers_name"), "suppliers", ["name"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("workflow_name", sa.String(length=255), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "retrying",
                "escalated",
                "cancelled",
                name="workflow_run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_step", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("checkpoints", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
        sa.UniqueConstraint(
            "workflow_name", "correlation_id", name=op.f("uq_workflow_runs_workflow_name")
        ),
    )
    op.create_index(
        op.f("ix_workflow_runs_correlation_id"), "workflow_runs", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_next_retry_at"), "workflow_runs", ["next_retry_at"], unique=False
    )
    op.create_index(op.f("ix_workflow_runs_status"), "workflow_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_workflow_runs_workflow_name"), "workflow_runs", ["workflow_name"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("workflow_run_id", sa.Uuid(), nullable=True),
        sa.Column("agent_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "retrying",
                "escalated",
                "cancelled",
                name="agent_run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("input_reference", sa.String(length=500), nullable=True),
        sa.Column("output_reference", sa.String(length=500), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column("safety_result", sa.JSON(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_agent_runs_workflow_run_id_workflow_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_agent_type"), "agent_runs", ["agent_type"], unique=False)
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_workflow_run_id"), "agent_runs", ["workflow_run_id"], unique=False
    )
    op.create_table(
        "customer_conversations",
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("marketplace", sa.String(length=100), nullable=False),
        sa.Column("marketplace_account_id", sa.String(length=255), nullable=False),
        sa.Column("external_conversation_id", sa.String(length=255), nullable=False),
        sa.Column("customer_reference", sa.String(length=255), nullable=False),
        sa.Column("classification", sa.String(length=100), nullable=True),
        sa.Column("risk_level", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "awaiting_approval",
                "escalated",
                "closed",
                name="conversation_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("assignee", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_customer_conversations_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_customer_conversations_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_conversations")),
        sa.UniqueConstraint(
            "marketplace",
            "marketplace_account_id",
            "external_conversation_id",
            name=op.f("uq_customer_conversations_marketplace"),
        ),
    )
    op.create_index(
        op.f("ix_customer_conversations_classification"),
        "customer_conversations",
        ["classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_conversations_order_id"),
        "customer_conversations",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_conversations_status"), "customer_conversations", ["status"], unique=False
    )
    op.create_table(
        "inventory_items",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("storage_location", sa.String(length=255), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "cost_basis >= 0", name=op.f("ck_inventory_items_nonnegative_cost_basis")
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0",
            name=op.f("ck_inventory_items_nonnegative_low_stock_threshold"),
        ),
        sa.CheckConstraint(
            "quantity_on_hand >= 0", name=op.f("ck_inventory_items_nonnegative_on_hand")
        ),
        sa.CheckConstraint(
            "reserved_quantity <= quantity_on_hand",
            name=op.f("ck_inventory_items_reservation_within_stock"),
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name=op.f("ck_inventory_items_nonnegative_reserved")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_inventory_items_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_items")),
        sa.UniqueConstraint("sku", "storage_location", name=op.f("uq_inventory_items_sku")),
    )
    op.create_index(
        op.f("ix_inventory_items_product_id"), "inventory_items", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_inventory_items_sku"), "inventory_items", ["sku"], unique=False)
    op.create_table(
        "supplier_quotes",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("external_quote_id", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("moq", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_supplier_quotes_nonnegative_lead_time")
        ),
        sa.CheckConstraint("moq > 0", name=op.f("ck_supplier_quotes_positive_moq")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_supplier_quotes_positive_quantity")),
        sa.CheckConstraint(
            "shipping_cost >= 0", name=op.f("ck_supplier_quotes_nonnegative_shipping_cost")
        ),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_supplier_quotes_nonnegative_unit_cost")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_supplier_quotes_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_supplier_quotes_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_quotes")),
        sa.UniqueConstraint(
            "supplier_id", "external_quote_id", name=op.f("uq_supplier_quotes_supplier_id")
        ),
    )
    op.create_index(
        op.f("ix_supplier_quotes_product_id"), "supplier_quotes", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_supplier_quotes_supplier_id"), "supplier_quotes", ["supplier_id"], unique=False
    )
    op.create_table(
        "customer_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column("external_message_id", sa.String(length=255), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="message_direction", native_enum=False),
            nullable=False,
        ),
        sa.Column("channel", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "draft",
                "approved",
                "sent",
                "failed",
                name="message_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "length(content) > 0", name=op.f("ck_customer_messages_nonempty_content")
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_customer_messages_approval_id_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["customer_conversations.id"],
            name=op.f("fk_customer_messages_conversation_id_customer_conversations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_messages")),
        sa.UniqueConstraint(
            "conversation_id",
            "external_message_id",
            name=op.f("uq_customer_messages_conversation_id"),
        ),
    )
    op.create_index(
        op.f("ix_customer_messages_conversation_id"),
        "customer_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_messages_status"), "customer_messages", ["status"], unique=False
    )
    op.create_table(
        "listing_drafts",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace", sa.String(length=100), nullable=False),
        sa.Column("listing_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("bullet_points", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("search_keywords", sa.JSON(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("proposed_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("image_requirements", sa.JSON(), nullable=False),
        sa.Column("marketplace_payload", sa.JSON(), nullable=False),
        sa.Column("validation_results", sa.JSON(), nullable=False),
        sa.Column(
            "approval_status",
            sa.Enum(
                "requested",
                "approved",
                "rejected",
                "expired",
                "cancelled",
                "executed",
                "execution_failed",
                name="listing_approval_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("provider_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "listing_version > 0", name=op.f("ck_listing_drafts_positive_listing_version")
        ),
        sa.CheckConstraint(
            "proposed_price >= 0", name=op.f("ck_listing_drafts_nonnegative_proposed_price")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_listing_drafts_inventory_item_id_inventory_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_drafts")),
        sa.UniqueConstraint(
            "inventory_item_id",
            "marketplace",
            "listing_version",
            name=op.f("uq_listing_drafts_inventory_item_id"),
        ),
    )
    op.create_index(
        op.f("ix_listing_drafts_inventory_item_id"),
        "listing_drafts",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_drafts_marketplace"), "listing_drafts", ["marketplace"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("external_line_id", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("reservation_reference", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_positive_quantity")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_items_nonnegative_unit_price")),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_order_items_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("order_id", "external_line_id", name=op.f("uq_order_items_order_id")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_items_sku"), "order_items", ["sku"], unique=False)
    op.create_table(
        "procurement_requests",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("selected_quote_id", sa.Uuid(), nullable=False),
        sa.Column("requested_quantity", sa.Integer(), nullable=False),
        sa.Column("estimated_landed_cost", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("recommendation_context", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "awaiting_approval",
                "ordered",
                "shipped",
                "received",
                "cancelled",
                name="procurement_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "estimated_landed_cost >= 0",
            name=op.f("ck_procurement_requests_nonnegative_estimated_landed_cost"),
        ),
        sa.CheckConstraint(
            "requested_quantity > 0",
            name=op.f("ck_procurement_requests_positive_requested_quantity"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_procurement_requests_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["selected_quote_id"],
            ["supplier_quotes.id"],
            name=op.f("fk_procurement_requests_selected_quote_id_supplier_quotes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procurement_requests")),
    )
    op.create_index(
        op.f("ix_procurement_requests_product_id"),
        "procurement_requests",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_requests_status"), "procurement_requests", ["status"], unique=False
    )
    op.create_table(
        "marketplace_listings",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace", sa.String(length=100), nullable=False),
        sa.Column("marketplace_account_id", sa.String(length=255), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("external_listing_id", sa.String(length=255), nullable=True),
        sa.Column(
            "publication_status",
            sa.Enum(
                "draft",
                "pending",
                "published",
                "failed",
                "archived",
                name="publication_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synchronised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["listing_drafts.id"],
            name=op.f("fk_marketplace_listings_draft_id_listing_drafts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_listings")),
        sa.UniqueConstraint("draft_id", name=op.f("uq_marketplace_listings_draft_id")),
        sa.UniqueConstraint(
            "marketplace",
            "marketplace_account_id",
            "external_listing_id",
            name="uq_marketplace_listing_external_id",
        ),
        sa.UniqueConstraint(
            "marketplace",
            "marketplace_account_id",
            "sku",
            name="uq_marketplace_listing_sku",
        ),
    )
    op.create_index(
        op.f("ix_marketplace_listings_publication_status"),
        "marketplace_listings",
        ["publication_status"],
        unique=False,
    )
    op.create_table(
        "purchase_orders",
        sa.Column("procurement_request_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("po_number", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("actual_landed_cost", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("terms", sa.JSON(), nullable=False),
        sa.Column("external_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "submitted",
                "shipped",
                "received",
                "cancelled",
                name="purchase_order_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_orders_positive_quantity")),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_purchase_orders_nonnegative_total")),
        sa.ForeignKeyConstraint(
            ["procurement_request_id"],
            ["procurement_requests.id"],
            name=op.f("fk_purchase_orders_procurement_request_id_procurement_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_purchase_orders_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("po_number", name=op.f("uq_purchase_orders_po_number")),
        sa.UniqueConstraint(
            "procurement_request_id", name=op.f("uq_purchase_orders_procurement_request_id")
        ),
    )
    op.create_index(op.f("ix_purchase_orders_status"), "purchase_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_table(
        "returns",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("disposition", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "approved",
                "received",
                "rejected",
                "completed",
                name="return_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_returns_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_returns_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"], ["order_items.id"], name=op.f("fk_returns_order_item_id_order_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
    )
    op.create_index(op.f("ix_returns_order_id"), "returns", ["order_id"], unique=False)
    op.create_index(op.f("ix_returns_status"), "returns", ["status"], unique=False)
    op.create_table(
        "inventory_movements",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column(
            "movement_type",
            sa.Enum(
                "receipt",
                "reservation",
                "release",
                "shipment",
                "return",
                "adjustment",
                name="inventory_movement_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "quantity_delta != 0", name=op.f("ck_inventory_movements_nonzero_quantity_delta")
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_inventory_movements_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_inventory_movements_purchase_order_id_purchase_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_inventory_movements_idempotency_key")),
    )
    op.create_index(
        op.f("ix_inventory_movements_inventory_item_id"),
        "inventory_movements",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_movement_type"),
        "inventory_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_table(
        "pricing_decisions",
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column("landed_cost", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("marketplace_fees", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("target_margin", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("minimum_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("proposed_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("contribution_margin", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("policy_result", sa.String(length=50), nullable=False),
        sa.Column("formula_version", sa.Integer(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "landed_cost >= 0", name=op.f("ck_pricing_decisions_nonnegative_landed_cost")
        ),
        sa.CheckConstraint(
            "minimum_price >= 0", name=op.f("ck_pricing_decisions_nonnegative_minimum_price")
        ),
        sa.CheckConstraint(
            "proposed_price >= minimum_price", name=op.f("ck_pricing_decisions_price_above_floor")
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
            name=op.f("fk_pricing_decisions_approval_id_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_pricing_decisions_inventory_item_id_inventory_items"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_pricing_decisions_listing_id_marketplace_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_decisions")),
    )
    op.create_index(
        op.f("ix_pricing_decisions_inventory_item_id"),
        "pricing_decisions",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_table(
        "refunds",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("return_id", sa.Uuid(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column("marketplace", sa.String(length=100), nullable=False),
        sa.Column("marketplace_account_id", sa.String(length=255), nullable=False),
        sa.Column("external_refund_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "approved",
                "processing",
                "completed",
                "failed",
                "cancelled",
                name="refund_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_refunds_positive_amount")),
        sa.ForeignKeyConstraint(
            ["approval_id"], ["approvals.id"], name=op.f("fk_refunds_approval_id_approvals")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_refunds_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["return_id"], ["returns.id"], name=op.f("fk_refunds_return_id_returns")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint(
            "marketplace",
            "marketplace_account_id",
            "external_refund_id",
            name=op.f("uq_refunds_marketplace"),
        ),
    )
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.create_index(op.f("ix_refunds_status"), "refunds", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_status"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_pricing_decisions_inventory_item_id"), table_name="pricing_decisions")
    op.drop_table("pricing_decisions")
    op.drop_index(op.f("ix_inventory_movements_movement_type"), table_name="inventory_movements")
    op.drop_index(
        op.f("ix_inventory_movements_inventory_item_id"), table_name="inventory_movements"
    )
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_returns_status"), table_name="returns")
    op.drop_index(op.f("ix_returns_order_id"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_status"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(
        op.f("ix_marketplace_listings_publication_status"), table_name="marketplace_listings"
    )
    op.drop_table("marketplace_listings")
    op.drop_index(op.f("ix_procurement_requests_status"), table_name="procurement_requests")
    op.drop_index(op.f("ix_procurement_requests_product_id"), table_name="procurement_requests")
    op.drop_table("procurement_requests")
    op.drop_index(op.f("ix_order_items_sku"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_listing_drafts_marketplace"), table_name="listing_drafts")
    op.drop_index(op.f("ix_listing_drafts_inventory_item_id"), table_name="listing_drafts")
    op.drop_table("listing_drafts")
    op.drop_index(op.f("ix_customer_messages_status"), table_name="customer_messages")
    op.drop_index(op.f("ix_customer_messages_conversation_id"), table_name="customer_messages")
    op.drop_table("customer_messages")
    op.drop_index(op.f("ix_supplier_quotes_supplier_id"), table_name="supplier_quotes")
    op.drop_index(op.f("ix_supplier_quotes_product_id"), table_name="supplier_quotes")
    op.drop_table("supplier_quotes")
    op.drop_index(op.f("ix_inventory_items_sku"), table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_product_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_customer_conversations_status"), table_name="customer_conversations")
    op.drop_index(op.f("ix_customer_conversations_order_id"), table_name="customer_conversations")
    op.drop_index(
        op.f("ix_customer_conversations_classification"), table_name="customer_conversations"
    )
    op.drop_table("customer_conversations")
    op.drop_index(op.f("ix_agent_runs_workflow_run_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_type"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_workflow_runs_workflow_name"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_status"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_next_retry_at"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_correlation_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_suppliers_name"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(op.f("ix_products_source_workflow_run_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_ordered_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_domain_events_outbox", table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_event_type"), table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_correlation_id"), table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_index("ix_audit_events_resource", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_expires_at"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action_type"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
