"""add listing agent traceability

Revision ID: 3dd83ccaa4b4
Revises: 5d4170f5351c
Create Date: 2026-08-15 10:40:29.079692
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3dd83ccaa4b4"
down_revision: str | None = "5d4170f5351c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("listing_drafts") as batch_op:
        batch_op.add_column(sa.Column("workflow_run_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("agent_run_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("approval_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("structured_ai_response", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("prompt_version", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("ai_provider", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("ai_model", sa.String(length=255), nullable=True))
        batch_op.create_index(
            op.f("ix_listing_drafts_workflow_run_id"), ["workflow_run_id"], unique=False
        )
        batch_op.create_unique_constraint(op.f("uq_listing_drafts_agent_run_id"), ["agent_run_id"])
        batch_op.create_unique_constraint(op.f("uq_listing_drafts_approval_id"), ["approval_id"])
        batch_op.create_foreign_key(
            op.f("fk_listing_drafts_approval_id_approvals"),
            "approvals",
            ["approval_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            op.f("fk_listing_drafts_agent_run_id_agent_runs"),
            "agent_runs",
            ["agent_run_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            op.f("fk_listing_drafts_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("listing_drafts") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_listing_drafts_workflow_run_id_workflow_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            op.f("fk_listing_drafts_agent_run_id_agent_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            op.f("fk_listing_drafts_approval_id_approvals"), type_="foreignkey"
        )
        batch_op.drop_constraint(op.f("uq_listing_drafts_approval_id"), type_="unique")
        batch_op.drop_constraint(op.f("uq_listing_drafts_agent_run_id"), type_="unique")
        batch_op.drop_index(op.f("ix_listing_drafts_workflow_run_id"))
        batch_op.drop_column("ai_model")
        batch_op.drop_column("ai_provider")
        batch_op.drop_column("prompt_version")
        batch_op.drop_column("structured_ai_response")
        batch_op.drop_column("approval_id")
        batch_op.drop_column("agent_run_id")
        batch_op.drop_column("workflow_run_id")
    # ### end Alembic commands ###
