"""add procurement delivery estimates

Revision ID: 5ac46cd984af
Revises: 5fc940752ddf
Create Date: 2026-08-15 10:26:01.385107
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5ac46cd984af"
down_revision: str | None = "5fc940752ddf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "procurement_requests",
        sa.Column("expected_arrival_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "purchase_orders",
        sa.Column("expected_arrival_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_orders", "expected_arrival_at")
    op.drop_column("procurement_requests", "expected_arrival_at")
    # ### end Alembic commands ###
