"""track purchase order receipts

Revision ID: 5d4170f5351c
Revises: 5ac46cd984af
Create Date: 2026-08-15 10:33:05.176903
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5d4170f5351c"
down_revision: str | None = "5ac46cd984af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_orders") as batch_op:
        batch_op.add_column(
            sa.Column("received_quantity", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.create_check_constraint(
            op.f("ck_purchase_orders_nonnegative_received_quantity"),
            "received_quantity >= 0",
        )
        batch_op.create_check_constraint(
            op.f("ck_purchase_orders_received_within_ordered"),
            "received_quantity <= quantity",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purchase_orders") as batch_op:
        batch_op.drop_constraint(op.f("ck_purchase_orders_received_within_ordered"), type_="check")
        batch_op.drop_constraint(
            op.f("ck_purchase_orders_nonnegative_received_quantity"), type_="check"
        )
        batch_op.drop_column("received_quantity")
    # ### end Alembic commands ###
