"""add intelligence ingestion traceability

Revision ID: 5fc940752ddf
Revises: 28a5e98a1a7d
Create Date: 2026-08-15 10:19:21.984887
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5fc940752ddf"
down_revision: str | None = "28a5e98a1a7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("procurement_requests") as batch_op:
        batch_op.add_column(sa.Column("workflow_run_id", sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint(
            op.f("uq_procurement_requests_workflow_run_id"), ["workflow_run_id"]
        )
        batch_op.create_foreign_key(
            op.f("fk_procurement_requests_workflow_run_id_workflow_runs"),
            "workflow_runs",
            ["workflow_run_id"],
            ["id"],
        )
    op.add_column(
        "products",
        sa.Column(
            "source_payload_hash",
            sa.String(length=64),
            server_default="legacy",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "source_payload_hash")
    with op.batch_alter_table("procurement_requests") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_procurement_requests_workflow_run_id_workflow_runs"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(op.f("uq_procurement_requests_workflow_run_id"), type_="unique")
        batch_op.drop_column("workflow_run_id")
    # ### end Alembic commands ###
