"""add event handler receipts

Revision ID: 85d3968e9db8
Revises: 3c43db34f536
Create Date: 2026-08-15 10:07:57.610325
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "85d3968e9db8"
down_revision: str | None = "3c43db34f536"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_handler_receipts",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("handler_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("completed", name="handler_receipt_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["domain_events.id"],
            name=op.f("fk_event_handler_receipts_event_id_domain_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_handler_receipts")),
        sa.UniqueConstraint(
            "event_id", "handler_name", name=op.f("uq_event_handler_receipts_event_id")
        ),
    )
    op.create_index(
        op.f("ix_event_handler_receipts_event_id"),
        "event_handler_receipts",
        ["event_id"],
        unique=False,
    )
    op.add_column("domain_events", sa.Column("workflow_id", sa.Uuid(), nullable=True))
    op.add_column(
        "domain_events",
        sa.Column("processing_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_index(
        op.f("ix_domain_events_workflow_id"), "domain_events", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domain_events_workflow_id"), table_name="domain_events")
    op.drop_column("domain_events", "processing_attempts")
    op.drop_column("domain_events", "workflow_id")
    op.drop_index(op.f("ix_event_handler_receipts_event_id"), table_name="event_handler_receipts")
    op.drop_table("event_handler_receipts")
    # ### end Alembic commands ###
